### ISSUE TITLE
Collector broken on Kubernetes 1.7

### ISSUE THREAD

**Issue by timothyb89** [monasca/monasca-helm#133]
Default deployment of Monasca on Minikube v0.21.0 running Kubernetes 1.7.0. The collector exits at startup:

```
[tim:~/projects/monasca-helm]↥ master+* 1 ± kubectl logs -n monasca monasca-agent-vlsq4 monasca-agent-collector-daemonset
+ PLUGIN_TEMPLATES=/templates
+ USER_PLUGINS=/plugins.d
+ AGENT_CONF=/etc/monasca/agent
+ AGENT_PLUGINS=/etc/monasca/agent/conf.d
+ mkdir -p /etc/monasca/agent/conf.d
+ [ true = true ]
+ python /kubernetes_get_host.py
No handlers could be found for logger "monasca_agent.collector.checks.utils"
Traceback (most recent call last):
  File "/kubernetes_get_host.py", line 6, in <module>
    print kubernetes_connector.get_agent_pod_host(return_host_name=True)
  File "/usr/lib/python2.7/site-packages/monasca_agent/collector/checks/utils.py", line 149, in get_agent_pod_host
    raise exceptions.KubernetesAPIConnectionError(exception_message)
monasca_agent.common.exceptions.KubernetesAPIConnectionError: Could not get agent pod from Kubernetes API to get host IP with error - Could not obtain data from https://10.0.0.1:443//api/v1/namespaces/monasca/pods/monasca-agent-vlsq4 with the given status code 404 and return text {
  "paths": [
    "/apis",
    "/apis/",
    "/apis/apiextensions.k8s.io",
    "/apis/apiextensions.k8s.io/v1beta1",
    "/metrics",
    "/version"
  ]
}
+ AGENT_HOSTNAME=
+ [ 1 != 0 ]
+ echo Error getting hostname from Kubernetes
+ return 1
Error getting hostname from Kubernetes
```

Possibly RBAC related, or the API endpoint just changed. Deploying via helm with `rbac.enabled=true` also seems broken right now, though.

**Comment by timothyb89** [comment]
I believe the root cause of this is that the upstream [KubernetesConnector](https://github.com/openstack/monasca-agent/blob/master/monasca_agent/collector/checks/utils.py#L149) is inserting an extra slash: `https://10.0.0.1:443//api/v1/...` should be `https://10.0.0.1:443/api/v1/`

That code hasn't changed in a while. Perhaps the Kubernetes API has become a bit more strict? It should be a simple enough fix regardless.

**Comment by amofakhar** [comment]
Seems it is fixed already in the latest push.

**Comment by timothyb89** [comment]
Yup, should be fixed now. Thanks for confirming!
